[package]
name = "mood"
version = "0.1.0"
authors = ["Mariot Tsitoara <mariot.tsitoara@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[workspace]
members = ["backend", "frontend"]
